### ISSUE TITLE
코드 맛깔나게 짜시네요.. 근데 이건 무슨 역할인가요?

### ISSUE THREAD

**Issue by chanmuzi** [BoocampMonster/Algorithm_Study#1]
https://github.com/BoocampMonster/Algorithm_Study/blob/7ef5ed957a5fe5c5c89fbec7d8f76f76bb8ea8cc/Week%201/1244_%EC%8A%A4%EC%9C%84%EC%B9%98%20%EC%BC%9C%EA%B3%A0%20%EB%81%84%EA%B8%B0/1244_%EC%9C%A0%EC%84%A0%EC%A2%85_%EC%8A%A4%EC%9C%84%EC%B9%98%20%EC%BC%9C%EA%B3%A0%20%EB%81%84%EA%B8%B0.py#L26

^1은 그냥 자기 자신 아닌가요..? 이거 무슨 역할인가요?
@Ssunbell

**Comment by hundredeuk2** [comment]
실험해보니까 홀수면 짝수가 되는 가장 가까운 큰 수, 짝수면 가장 가까운 작은 수로 변환하네요? 대박이네

예를 들면
```
l = [0,1,2,3,4] => 1 0 3 2 5
```
```
l = [0,2,4,8,10] => 1,3,5,7,9,11
```
```
l = [1,3,5,7,9] => 0,2,4,8,10
```
이렇게 출력됩니다.

따라서 0과 1만 있는 switch 리스트에 딱 적합하군요.. 오늘도 하나 배워갑니다.

**Comment by Ssunbell** [comment]
이게 비트 연산자라는 건데,,,
비트 연산자가,,, 컴파일 수준에서 접근해서,,, 매우 빠릅니다,,,
김밥 하나와,,, [링크](http://www.tcpschool.com/c/c_operator_bitwise) 하나 남겨둡니다,,, @))))))))
